version: 2.0

jobs:
  debianStable_gcrypt:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run:
          command: |
            apt update && apt -y install git gcc clang cmake libcriterion-dev libgcrypt20-dev
            mkdir build && cd "$_"
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=ON ..
            make && make install
            ./tests/test_base32encode
            ./tests/test_base32decode
            ./tests/test_cotp
  ubuntu2204_gcrypt:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          command: |
            apt update && apt -y install git gcc clang cmake libcriterion-dev libgcrypt20-dev
            mkdir build && cd "$_"
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=ON ..
            make && make install
            ./tests/test_base32encode
            ./tests/test_base32decode
            ./tests/test_cotp
  debianStable_openssl:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run:
          command: |
            apt update && apt -y install git gcc clang cmake libcriterion-dev libssl-dev
            mkdir build && cd "$_"
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=ON -DHMAC_WRAPPER=openssl ..
            make && make install
            ./tests/test_base32encode
            ./tests/test_base32decode
            ./tests/test_cotp
  ubuntu2204_openssl:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          command: |
            apt update && apt -y install git gcc clang cmake libcriterion-dev libssl-dev
            mkdir build && cd "$_"
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=ON -DHMAC_WRAPPER=openssl ..
            make && make install
            ./tests/test_base32encode
            ./tests/test_base32decode
            ./tests/test_cotp

workflows:
  version: 2
  build:
    jobs:
      - debianStable_gcrypt
      - ubuntu2204_gcrypt
      - debianStable_openssl
      - ubuntu2204_openssl
